### ISSUE TITLE
RFCx developer should be able to find a guardian by phone number

### ISSUE THREAD

**Issue by rassokhin-s** [rfcx/rfcx-guardian-android#131]
I as RFCx developer need a way to find guardian guid / name by phone number to backtrack which guardian sends a lot of sms messages to Twilio service.

At the current time there are a lot of phone numbers which don't exist in our database. For example: +17876900415 +13467870964

**Comment by antonyharfield** [comment]
We have switched off sms for all Guardians except India. Is this still relevant @rassokhin-s?
