### ISSUE TITLE
Write logging code for new Bosch gas sensor

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/rfcx-guardian-android#203]
Ideas
- Create a new repository for experiments
- Use another i2c sensor to test it

**Comment by KritsanaMike** [comment]
Software for BME688 :
- https://www.bosch-sensortec.com/software-tools/software/BME688-software/

Library and Example code : 
- https://github.com/Zanduino/BME680
- https://create.arduino.cc/projecthub/dragos-iosub/bme688-first-ai-gas-sensor-arduino-how-to-b8a0a6

**Comment by KritsanaMike** [comment]
Arduino code for BME688 Datalogger
https://github.com/rfcx/guardian-hardware-experiments/tree/develop/BME688/Arduino-code
