### ISSUE TITLE
Setup Rabbitmq

### ISSUE THREAD

**Issue by RatreeOchn** [rfcx/rfcx-guardian-android#333]
- Setup non-prod rabbitMQ
- How do we deploy rabbitMQ to make it work for Guardian
- Having Load balance using for rabbitMQ (SSL certificate)
- Trying rabbitMQ locally
- Deploy rabbitmq to k8s
- Deploy rabbitmq to locally
- Testing namespace with local guardian
- 3.8.7 rabbitmq with helm

**Comment by Tooseriuz** [comment]
run on kubernates cluster

**Comment by Tooseriuz** [comment]
make it running on our sub-domain
Enable TSL/SSL cert for guardian connection
Username and password from guardian information

**Comment by Tooseriuz** [comment]
Fix java client cannot connect to server
Username and password from guardian information

**Comment by Tooseriuz** [comment]
Setup RFCx ssl
Username and password from guardian information
