### ISSUE TITLE
Add to RFCx Android Image: Add busybox binary

### ISSUE THREAD

**Issue by topherwhite** [rfcx/rfcx-guardian-android#60]
In the default Android image for OrangePi, please add the `busybox` binary to `/system/xbin/busybox` 
And ensure that it is universally executable.
Attached to this issue is a zipped binary of busybox, which should be executable on the OrangePi when unzipped and correctly placed.
[busybox.zip](https://github.com/rfcx/rfcx-guardian-android/files/6097372/busybox.zip)

Thanks!

**Comment by topherwhite** [comment]
FYI, I got the binary from this APK, but the binary alone has been confirmed to work
[ru.meefik.busybox_46.apk.zip](https://github.com/rfcx/rfcx-guardian-android/files/6097386/ru.meefik.busybox_46.apk.zip)

**Comment by Tooseriuz** [comment]
this update was released in https://github.com/rfcx/guardian-opi-android-source/releases/tag/0.2.1
